import { WorkoutPlan } from './types';

export const WORKOUT_DATA: WorkoutPlan = {
  "Beginner": [
    {
      "name": "Jumping Jacks",
      "duration": 30,
      "description": "Full body warm-up cardio exercise",
      "difficulty": "Easy",
      "muscle": "Full Body",
      "instruction3D": "jumping_jacks",
      "videoLink": "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
      "thumbnail": "https://img.youtube.com/vi/c4DAnQ6DtF8/hqdefault.jpg",
      "formTips": ["Keep arms straight", "Land softly on your feet"]
    },
    {
      "name": "Wall Push-ups",
      "duration": 30,
      "description": "Beginner push-up variation focusing on chest and triceps.",
      "difficulty": "Easy",
      "muscle": "Chest",
      "instruction3D": "wall_pushups",
      "videoLink": "https://www.youtube.com/watch?v=0pkjOk0EiAk",
      "thumbnail": "https://img.youtube.com/vi/0pkjOk0EiAk/hqdefault.jpg",
      "formTips": ["Maintain a straight line from head to heels", "Control the descent"]
    },
    {
      "name": "Bodyweight Squats",
      "duration": 40,
      "description": "Fundamental lower body exercise for legs and glutes.",
      "difficulty": "Easy",
      "muscle": "Legs",
      "instruction3D": "squats",
      "videoLink": "https://www.youtube.com/watch?v=aclHkVaku9U",
      "thumbnail": "https://img.youtube.com/vi/aclHkVaku9U/hqdefault.jpg",
      "formTips": ["Weight on your heels", "Keep chest up"]
    },
    {
      "name": "Knee Push-ups",
      "duration": 30,
      "description": "Modified push-up to build upper body strength.",
      "difficulty": "Easy",
      "muscle": "Chest",
      "instruction3D": "knee_pushups",
      "videoLink": "https://www.youtube.com/watch?v=IODxDxX7oi4",
      "thumbnail": "https://img.youtube.com/vi/IODxDxX7oi4/hqdefault.jpg",
      "formTips": ["Don't let your lower back sag", "Core engaged"]
    },
    {
      "name": "Plank Hold",
      "duration": 30,
      "description": "Static core stability exercise.",
      "difficulty": "Easy",
      "muscle": "Core",
      "instruction3D": "plank",
      "videoLink": "https://www.youtube.com/watch?v=pSHjTRCQxIw",
      "thumbnail": "https://img.youtube.com/vi/pSHjTRCQxIw/hqdefault.jpg",
      "formTips": ["Keep body straight", "Squeeze glutes"]
    },
    {
      "name": "Glute Bridge",
      "duration": 30,
      "description": "Activates and strengthens glutes and hamstrings.",
      "difficulty": "Easy",
      "muscle": "Glutes",
      "instruction3D": "glute_bridge",
      "videoLink": "https://www.youtube.com/watch?v=wPM8icPu6H8",
      "thumbnail": "https://img.youtube.com/vi/wPM8icPu6H8/hqdefault.jpg",
      "formTips": ["Push through heels", "Pause at the top"]
    },
    {
      "name": "High Knees",
      "duration": 30,
      "description": "High-intensity cardio and leg coordination.",
      "difficulty": "Easy",
      "muscle": "Legs",
      "instruction3D": "high_knees",
      "videoLink": "https://www.youtube.com/watch?v=OAJ_J3EZkdY",
      "thumbnail": "https://img.youtube.com/vi/OAJ_J3EZkdY/hqdefault.jpg",
      "formTips": ["Pump your arms", "Land on balls of feet"]
    },
    {
      "name": "Standing Calf Raises",
      "duration": 30,
      "description": "Targeting the lower leg muscles.",
      "difficulty": "Easy",
      "muscle": "Calves",
      "instruction3D": "calf_raises",
      "videoLink": "https://www.youtube.com/watch?v=-M4-G8p8fmc",
      "thumbnail": "https://img.youtube.com/vi/-M4-G8p8fmc/hqdefault.jpg",
      "formTips": ["Full range of motion", "Controlled movement"]
    },
    {
      "name": "Arm Circles",
      "duration": 30,
      "description": "Dynamic shoulder warm-up.",
      "difficulty": "Easy",
      "muscle": "Shoulders",
      "instruction3D": "arm_circles",
      "videoLink": "https://www.youtube.com/watch?v=140RTNMciH8",
      "thumbnail": "https://img.youtube.com/vi/140RTNMciH8/hqdefault.jpg",
      "formTips": ["Keep arms at shoulder height", "Small controlled circles"]
    },
    {
      "name": "Standing Side Bends",
      "duration": 30,
      "description": "Improving lateral core flexibility.",
      "difficulty": "Easy",
      "muscle": "Core",
      "instruction3D": "side_bends",
      "videoLink": "https://www.youtube.com/watch?v=0x4v7v2h2Mc",
      "thumbnail": "https://img.youtube.com/vi/0x4v7v2h2Mc/hqdefault.jpg",
      "formTips": ["Don't lean forward or backward", "Controlled stretch"]
    },
    {
      "name": "March in Place",
      "duration": 30,
      "description": "Low intensity active recovery or warm-up.",
      "difficulty": "Easy",
      "muscle": "Full Body",
      "instruction3D": "march",
      "videoLink": "https://www.youtube.com/watch?v=rvqLVxYqEvo",
      "thumbnail": "https://img.youtube.com/vi/rvqLVxYqEvo/hqdefault.jpg",
      "formTips": ["Swing arms naturally", "Upright posture"]
    },
    {
      "name": "Bird Dog",
      "duration": 30,
      "description": "Core stability and balance exercise.",
      "difficulty": "Easy",
      "muscle": "Core",
      "instruction3D": "bird_dog",
      "videoLink": "https://www.youtube.com/watch?v=wiFNA3sqjCA",
      "thumbnail": "https://img.youtube.com/vi/wiFNA3sqjCA/hqdefault.jpg",
      "formTips": ["Neutral spine", "Don't arch back"]
    },
    {
      "name": "Dead Bug",
      "duration": 30,
      "description": "Deep core activation.",
      "difficulty": "Easy",
      "muscle": "Core",
      "instruction3D": "dead_bug",
      "videoLink": "https://www.youtube.com/watch?v=g_BYB0R-4Ws",
      "thumbnail": "https://img.youtube.com/vi/g_BYB0R-4Ws/hqdefault.jpg",
      "formTips": ["Lower back pressed to floor", "Exhale on extension"]
    },
    {
      "name": "Wall Sit",
      "duration": 30,
      "description": "Isometric leg strength.",
      "difficulty": "Easy",
      "muscle": "Legs",
      "instruction3D": "wall_sit",
      "videoLink": "https://www.youtube.com/watch?v=y-wV4Venusw",
      "thumbnail": "https://img.youtube.com/vi/y-wV4Venusw/hqdefault.jpg",
      "formTips": ["90 degree angle at knees", "Back flat against wall"]
    },
    {
      "name": "Scapular Squeezes",
      "duration": 30,
      "description": "Improve posture and back activation.",
      "difficulty": "Easy",
      "muscle": "Back",
      "instruction3D": "scapular_squeezes",
      "videoLink": "https://www.youtube.com/watch?v=GExmGvD8-tM",
      "thumbnail": "https://img.youtube.com/vi/GExmGvD8-tM/hqdefault.jpg",
      "formTips": ["Squeeze shoulder blades", "Depress shoulders down"]
    }
  ],
  "Intermediate": [
    {
      "name": "Standard Push-ups",
      "duration": 40,
      "description": "Classic upper body compound movement.",
      "difficulty": "Medium",
      "muscle": "Chest",
      "instruction3D": "standard_pushups",
      "videoLink": "https://www.youtube.com/watch?v=_l3ySVKYVJ8",
      "thumbnail": "https://img.youtube.com/vi/_l3ySVKYVJ8/hqdefault.jpg",
      "formTips": ["Elbows at 45 degrees", "Full lock out at top"]
    },
    {
      "name": "Walking Lunges",
      "duration": 40,
      "description": "Dynamic leg strength and balance.",
      "difficulty": "Medium",
      "muscle": "Legs",
      "instruction3D": "lunges",
      "videoLink": "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
      "thumbnail": "https://img.youtube.com/vi/QOVaHwm-Q6U/hqdefault.jpg",
      "formTips": ["Take big steps", "Keep torso upright"]
    },
    {
      "name": "Mountain Climbers",
      "duration": 40,
      "description": "Core and cardio endurance.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "mountain_climbers",
      "videoLink": "https://www.youtube.com/watch?v=nmwgirgXLYM",
      "thumbnail": "https://img.youtube.com/vi/nmwgirgXLYM/hqdefault.jpg",
      "formTips": ["Hips low", "Driven knees to chest"]
    },
    {
      "name": "Burpees",
      "duration": 40,
      "description": "Full body explosive conditioning.",
      "difficulty": "Medium",
      "muscle": "Full Body",
      "instruction3D": "burpees",
      "videoLink": "https://www.youtube.com/watch?v=TU8QYVW0gDU",
      "thumbnail": "https://img.youtube.com/vi/TU8QYVW0gDU/hqdefault.jpg",
      "formTips": ["Jump high", "Land in a strong plank"]
    },
    {
      "name": "Plank Shoulder Taps",
      "duration": 40,
      "description": "Anti-rotation core stability.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "shoulder_taps",
      "videoLink": "https://www.youtube.com/watch?v=5bR-1t9y3nE",
      "thumbnail": "https://img.youtube.com/vi/5bR-1t9y3nE/hqdefault.jpg",
      "formTips": ["Minimize hip sway", "Wide stance for stability"]
    },
    {
      "name": "Diamond Push-ups",
      "duration": 30,
      "description": "Targeting the triceps and inner chest.",
      "difficulty": "Medium",
      "muscle": "Triceps",
      "instruction3D": "diamond_pushups",
      "videoLink": "https://www.youtube.com/watch?v=J0DnG1_S92I",
      "thumbnail": "https://img.youtube.com/vi/J0DnG1_S92I/hqdefault.jpg",
      "formTips": ["Hands form a diamond shape", "Elbows close to ribs"]
    },
    {
      "name": "Dips on Bench",
      "duration": 40,
      "description": "Upper body push focus.",
      "difficulty": "Medium",
      "muscle": "Triceps",
      "instruction3D": "bench_dips",
      "videoLink": "https://www.youtube.com/watch?v=0326dy_-CzM",
      "thumbnail": "https://img.youtube.com/vi/0326dy_-CzM/hqdefault.jpg",
      "formTips": ["Keep back close to bench", "90 degree bend at bottom"]
    },
    {
      "name": "Chin-ups",
      "duration": 30,
      "description": "Vertical pull focused on biceps and lats.",
      "difficulty": "Medium",
      "muscle": "Back",
      "instruction3D": "pullups",
      "videoLink": "https://www.youtube.com/watch?v=9S_vId_Z-3k",
      "thumbnail": "https://img.youtube.com/vi/9S_vId_Z-3k/hqdefault.jpg",
      "formTips": ["Palms facing you", "Pull till chin clears bar"]
    },
    {
      "name": "Box Jumps",
      "duration": 40,
      "description": "Plyometric lower body explosiveness.",
      "difficulty": "Medium",
      "muscle": "Legs",
      "instruction3D": "box_jumps",
      "videoLink": "https://www.youtube.com/watch?v=NBY9-kutuFE",
      "thumbnail": "https://img.youtube.com/vi/NBY9-kutuFE/hqdefault.jpg",
      "formTips": ["Land softly", "Step down, don't jump down"]
    },
    {
      "name": "Bicycle Crunches",
      "duration": 45,
      "description": "Targeting obliques and rectus abdominis.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "bicycle_crunches",
      "videoLink": "https://www.youtube.com/watch?v=9FGilxCbdz8",
      "thumbnail": "https://img.youtube.com/vi/9FGilxCbdz8/hqdefault.jpg",
      "formTips": ["Rotate through the core", "Opposite elbow to knee"]
    },
    {
      "name": "Incline Push-ups",
      "duration": 40,
      "description": "Emphasizing lower chest.",
      "difficulty": "Medium",
      "muscle": "Chest",
      "instruction3D": "incline_pushups",
      "videoLink": "https://www.youtube.com/watch?v=Me9bHFAxn8A",
      "thumbnail": "https://img.youtube.com/vi/Me9bHFAxn8A/hqdefault.jpg",
      "formTips": ["Hands on elevated surface", "Body in straight line"]
    },
    {
      "name": "Decline Push-ups",
      "duration": 30,
      "description": "Emphasizing upper chest.",
      "difficulty": "Medium",
      "muscle": "Chest",
      "instruction3D": "decline_pushups",
      "videoLink": "https://www.youtube.com/watch?v=SKPab2YC8BE",
      "thumbnail": "https://img.youtube.com/vi/SKPab2YC8BE/hqdefault.jpg",
      "formTips": ["Feet on elevated surface", "Tuck chin slightly"]
    },
    {
      "name": "Archer Squats",
      "duration": 40,
      "description": "Lateral leg strength and mobility.",
      "difficulty": "Medium",
      "muscle": "Legs",
      "instruction3D": "archer_squats",
      "videoLink": "https://www.youtube.com/watch?v=OEn2o7_L0pQ",
      "thumbnail": "https://img.youtube.com/vi/OEn2o7_L0pQ/hqdefault.jpg",
      "formTips": ["One leg straight", "Keep heel of bent leg on ground"]
    },
    {
      "name": "Hollow Body Hold",
      "duration": 30,
      "description": "Foundational calisthenics core position.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "hollow_body",
      "videoLink": "https://www.youtube.com/watch?v=LlV9u_RAtL0",
      "thumbnail": "https://img.youtube.com/vi/LlV9u_RAtL0/hqdefault.jpg",
      "formTips": ["Lower back glued to floor", "Toes pointed"]
    },
    {
      "name": "Side Plank Hold",
      "duration": 30,
      "description": "Lateral core stability.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "side_plank",
      "videoLink": "https://www.youtube.com/watch?v=NXr4Fwku60g",
      "thumbnail": "https://img.youtube.com/vi/NXr4Fwku60g/hqdefault.jpg",
      "formTips": ["Stack your feet", "Lift hips high"]
    },
    {
      "name": "Russian Twists",
      "duration": 40,
      "description": "Rotational core strength.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "russian_twists",
      "videoLink": "https://www.youtube.com/watch?v=wkD8rjk6raI",
      "thumbnail": "https://img.youtube.com/vi/wkD8rjk6raI/hqdefault.jpg",
      "formTips": ["Feet off ground for challenge", "Touch floor each side"]
    },
    {
      "name": "Superman Hold",
      "duration": 30,
      "description": "Lower back and posterior chain activation.",
      "difficulty": "Medium",
      "muscle": "Back",
      "instruction3D": "superman",
      "videoLink": "https://www.youtube.com/watch?v=z6PJMT2y8GQ",
      "thumbnail": "https://img.youtube.com/vi/z6PJMT2y8GQ/hqdefault.jpg",
      "formTips": ["Lift chest and thighs", "Gaze down at floor"]
    },
    {
      "name": "Leg Raises",
      "duration": 40,
      "description": "Lower abdominal strength.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "leg_raises",
      "videoLink": "https://www.youtube.com/watch?v=l4kQd9eWclE",
      "thumbnail": "https://img.youtube.com/vi/l4kQd9eWclE/hqdefault.jpg",
      "formTips": ["Keep legs straight", "Slow and controlled descent"]
    },
    {
      "name": "Flutter Kicks",
      "duration": 40,
      "description": "Endurance core exercise.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "flutter_kicks",
      "videoLink": "https://www.youtube.com/watch?v=eGZpXRAXv5U",
      "thumbnail": "https://img.youtube.com/vi/eGZpXRAXv5U/hqdefault.jpg",
      "formTips": ["Small rapid kicks", "Hands under glutes for support"]
    },
    {
      "name": "Toe Touches",
      "duration": 40,
      "description": "Upper core compression.",
      "difficulty": "Medium",
      "muscle": "Core",
      "instruction3D": "toe_touches",
      "videoLink": "https://www.youtube.com/watch?v=pAnA8qG08-E",
      "thumbnail": "https://img.youtube.com/vi/pAnA8qG08-E/hqdefault.jpg",
      "formTips": ["Reach for the toes", "Exhale on way up"]
    }
  ],
  "Advanced": [
    {
      "name": "Pull-ups",
      "duration": 45,
      "description": "The gold standard for upper body pulling strength.",
      "difficulty": "Hard",
      "muscle": "Back",
      "instruction3D": "pullups",
      "videoLink": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
      "thumbnail": "https://img.youtube.com/vi/eGo4IYlbE5g/hqdefault.jpg",
      "formTips": ["Full extension at bottom", "Chin over bar"]
    },
    {
      "name": "Handstand Push-ups",
      "duration": 30,
      "description": "Elite shoulder and tricep strength.",
      "difficulty": "Hard",
      "muscle": "Shoulders",
      "instruction3D": "handstand_pushups",
      "videoLink": "https://www.youtube.com/watch?v=tKjcgfu44sI",
      "thumbnail": "https://img.youtube.com/vi/tKjcgfu44sI/hqdefault.jpg",
      "formTips": ["Head touches floor gently", "Explosive lockout"]
    },
    {
      "name": "Pistol Squats",
      "duration": 40,
      "description": "Advanced single leg squat for strength and mobility.",
      "difficulty": "Hard",
      "muscle": "Legs",
      "instruction3D": "pistols",
      "videoLink": "https://www.youtube.com/watch?v=vq5-vdgJc0I",
      "thumbnail": "https://img.youtube.com/vi/vq5-vdgJc0I/hqdefault.jpg",
      "formTips": ["Heel stays down", "Free leg straight and parallel"]
    },
    {
      "name": "Muscle-ups",
      "duration": 40,
      "description": "Transitioning from a pull-up to a dip.",
      "difficulty": "Hard",
      "muscle": "Upper Body",
      "instruction3D": "muscle_ups",
      "videoLink": "https://www.youtube.com/watch?v=2Y2XwqF3X4I",
      "thumbnail": "https://img.youtube.com/vi/2Y2XwqF3X4I/hqdefault.jpg",
      "formTips": ["False grip helps", "Lean forward through the transition"]
    },
    {
      "name": "Clap Push-ups",
      "duration": 40,
      "description": "Plyometric upper body strength.",
      "difficulty": "Hard",
      "muscle": "Chest",
      "instruction3D": "clap_pushups",
      "videoLink": "https://www.youtube.com/watch?v=EYwWCgM198U",
      "thumbnail": "https://img.youtube.com/vi/EYwWCgM198U/hqdefault.jpg",
      "formTips": ["Push as hard as possible", "Gentle landing"]
    },
    {
      "name": "Dragon Flag",
      "duration": 30,
      "description": "Elite core compression and control.",
      "difficulty": "Hard",
      "muscle": "Core",
      "instruction3D": "dragon_flag",
      "videoLink": "https://www.youtube.com/watch?v=f7BqS8AFrXo",
      "thumbnail": "https://img.youtube.com/vi/f7BqS8AFrXo/hqdefault.jpg",
      "formTips": ["Only shoulders on bench", "Full tension through body"]
    },
    {
      "name": "L-Sit Hold",
      "duration": 30,
      "description": "Isometric core and tricep hold.",
      "difficulty": "Hard",
      "muscle": "Core",
      "instruction3D": "l_sit",
      "videoLink": "https://www.youtube.com/watch?v=IUZJoP8E0lo",
      "thumbnail": "https://img.youtube.com/vi/IUZJoP8E0lo/hqdefault.jpg",
      "formTips": ["Depress shoulders", "Quads tight"]
    },
    {
      "name": "Archer Push-ups",
      "duration": 40,
      "description": "Unilateral upper body push variation.",
      "difficulty": "Hard",
      "muscle": "Chest",
      "instruction3D": "archer_pushups",
      "videoLink": "https://www.youtube.com/watch?v=0h6Yp7q6Fms",
      "thumbnail": "https://img.youtube.com/vi/0h6Yp7q6Fms/hqdefault.jpg",
      "formTips": ["Side arm straight", "Lower controlled"]
    },
    {
      "name": "Human Flag Practice",
      "duration": 30,
      "description": "Progressing towards the ultimate lateral hold.",
      "difficulty": "Hard",
      "muscle": "Full Body",
      "instruction3D": "human_flag",
      "videoLink": "https://www.youtube.com/watch?v=l_0r9G9gndE",
      "thumbnail": "https://img.youtube.com/vi/l_0r9G9gndE/hqdefault.jpg",
      "formTips": ["Push top arm, pull bottom arm", "Invert slightly for balance"]
    },
    {
      "name": "V-Ups",
      "duration": 45,
      "description": "Intense core compression.",
      "difficulty": "Hard",
      "muscle": "Core",
      "instruction3D": "v_ups",
      "videoLink": "https://www.youtube.com/watch?v=7uHeE6K4fO0",
      "thumbnail": "https://img.youtube.com/vi/7uHeE6K4fO0/hqdefault.jpg",
      "formTips": ["Touch toes at the top", "Keep legs straight"]
    },
    {
      "name": "One Arm Push-up",
      "duration": 30,
      "description": "High level unilateral push strength.",
      "difficulty": "Hard",
      "muscle": "Chest",
      "instruction3D": "one_arm_pushup",
      "videoLink": "https://www.youtube.com/watch?v=fpx_vV3S2M0",
      "thumbnail": "https://img.youtube.com/vi/fpx_vV3S2M0/hqdefault.jpg",
      "formTips": ["Wide feet for stability", "Shoulders square to floor"]
    },
    {
      "name": "Pseudo Planche Push-ups",
      "duration": 40,
      "description": "Leaning forward to shift weight to shoulders.",
      "difficulty": "Hard",
      "muscle": "Shoulders",
      "instruction3D": "pseudo_planche",
      "videoLink": "https://www.youtube.com/watch?v=1Fpxn-B43-0",
      "thumbnail": "https://img.youtube.com/vi/1Fpxn-B43-0/hqdefault.jpg",
      "formTips": ["Protracted scapula", "Hands by the waist"]
    },
    {
      "name": "Back Lever Hold",
      "duration": 20,
      "description": "Static pull position on bars.",
      "difficulty": "Hard",
      "muscle": "Back",
      "instruction3D": "back_lever",
      "videoLink": "https://www.youtube.com/watch?v=TAsP2yFpiz0",
      "thumbnail": "https://img.youtube.com/vi/TAsP2yFpiz0/hqdefault.jpg",
      "formTips": ["Round upper back slightly", "Core tight"]
    },
    {
      "name": "Front Lever Practice",
      "duration": 20,
      "description": "Tucked front lever for pulling power.",
      "difficulty": "Hard",
      "muscle": "Core",
      "instruction3D": "front_lever",
      "videoLink": "https://www.youtube.com/watch?v=3uR_v5f62o8",
      "thumbnail": "https://img.youtube.com/vi/3uR_v5f62o8/hqdefault.jpg",
      "formTips": ["Pulling bar to waist", "Lats fully engaged"]
    },
    {
      "name": "Tuck Planche Hold",
      "duration": 20,
      "description": "Initial planche progression.",
      "difficulty": "Hard",
      "muscle": "Shoulders",
      "instruction3D": "planche",
      "videoLink": "https://www.youtube.com/watch?v=F3_l_h8fMzs",
      "thumbnail": "https://img.youtube.com/vi/F3_l_h8fMzs/hqdefault.jpg",
      "formTips": ["Lean forward deeply", "Lock elbows out"]
    },
    {
      "name": "Wide Grip Pull-ups",
      "duration": 40,
      "description": "Focusing on the outer lats.",
      "difficulty": "Hard",
      "muscle": "Back",
      "instruction3D": "pullups_wide",
      "videoLink": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
      "thumbnail": "https://img.youtube.com/vi/eGo4IYlbE5g/hqdefault.jpg",
      "formTips": ["Hands wider than shoulders", "Touch chest to bar"]
    },
    {
      "name": "Explosive Pull-ups",
      "duration": 30,
      "description": "Pulling as high as possible.",
      "difficulty": "Hard",
      "muscle": "Back",
      "instruction3D": "pullups_explosive",
      "videoLink": "https://www.youtube.com/watch?v=rC-3D5zF2yY",
      "thumbnail": "https://img.youtube.com/vi/rC-3D5zF2yY/hqdefault.jpg",
      "formTips": ["Pull till bar touches stomach", "Maximum velocity"]
    },
    {
      "name": "Hanging Leg Raises",
      "duration": 40,
      "description": "Intense core compression while hanging.",
      "difficulty": "Hard",
      "muscle": "Core",
      "instruction3D": "hanging_leg_raises",
      "videoLink": "https://www.youtube.com/watch?v=hZInaD0dFyo",
      "thumbnail": "https://img.youtube.com/vi/hZInaD0dFyo/hqdefault.jpg",
      "formTips": ["No swinging", "Toes to bar"]
    },
    {
      "name": "Russian Dip on Parallel Bars",
      "duration": 30,
      "description": "Targeting shoulders and triceps.",
      "difficulty": "Hard",
      "muscle": "Triceps",
      "instruction3D": "russian_dips",
      "videoLink": "https://www.youtube.com/watch?v=q6g-I_p0U-4",
      "thumbnail": "https://img.youtube.com/vi/q6g-I_p0U-4/hqdefault.jpg",
      "formTips": ["Forearms flat on bar", "Explode up"]
    },
    {
      "name": "Slow Negatives (All)",
      "duration": 40,
      "description": "5-second eccentric movement for all pulls.",
      "difficulty": "Hard",
      "muscle": "Full Body",
      "instruction3D": "slow_negatives",
      "videoLink": "https://www.youtube.com/watch?v=P_VIs8w1N2Y",
      "thumbnail": "https://img.youtube.com/vi/P_VIs8w1N2Y/hqdefault.jpg",
      "formTips": ["Uniform speed throughout", "Don't drop at the bottom"]
    }
  ]
};
